language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "pypy3"
matrix:
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
    - python: "3.3"
    - python: "3.4"
before_script:
  - '[ "${TRAVIS_PYTHON_VERSION}" = "2.6" ] && travis_retry pip install unittest2 || /bin/true'
script: python setup.py test
